vich_uploader:
    db_driver: orm
    
    mappings:
        hotel_image:
            uri_prefix: /images/proporties
            upload_destination: '%kernel.project_dir%/public/images/proporties'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
